CREATE PROCEDURE "CCEJ_VIRTUAL"."ZJ_AccountPL.SupportFee::ZJ_SUPPORTFEE_RES_UPDATE" ( IN IP_DOC_TYPE NVARCHAR(10), IN IP_GL NCLOB,
IN IP_WW220 NCLOB,
IN IP_WW223 NCLOB,
IN IP_WW214 NCLOB,
IN IP_PGL NCLOB,
IN IP_RES TABLE (
"PALEDGER" NVARCHAR(2),
"VRGAR" NVARCHAR(1),
"PERIO" NVARCHAR(7),
"BELNR" NVARCHAR(10),
"POSNR" NVARCHAR(6),
"GJAHR" NVARCHAR(4),
"BUDAT" NVARCHAR(8),
"KNDNR" NVARCHAR(10),
"ARTNR" NVARCHAR(18),
"BUKRS" NVARCHAR(4),
"KOKRS" NVARCHAR(4),
"WERKS" NVARCHAR(4),
"VKORG" NVARCHAR(4),
"VTWEG" NVARCHAR(2),
"SPART" NVARCHAR(2),
"PRCTR" NVARCHAR(10),
"WW207" NVARCHAR(10),
"WW214" NVARCHAR(7),
"WW220" NVARCHAR(3),
"WW223" NVARCHAR(3),
"VV557" DECIMAL(15,2),
"VV582" DECIMAL(15,2),
"VV529" DECIMAL(15,2),
"BLART" NVARCHAR(2),
"EXPENSE_GL" NVARCHAR(10),
"WW233" NVARCHAR(3),
"WW237" NVARCHAR(3),
"KSTAR" NVARCHAR(10),
"POST_GL" NVARCHAR(10),
CRDATE DATE,
CRTIME TIME,
CRNAME NVARCHAR(12)
)
  ) 
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER 
--DEFAULT SCHEMA <default_schema_name>
--READS SQL DATA 
AS
BEGIN
/***************************** 
Write your procedure logic 
 *****************************/
 DECLARE LV_PERIO NVARCHAR(7):= '';
 DECLARE LV_BUKRS NVARCHAR(4):='';
 DECLARE LV_COUNT INTEGER;
 DECLARE LV_WCLAUSE NCLOB:='';
 Declare LV_SQL NCLOB:='';
 
 IF IP_DOC_TYPE != '' THEN
   LV_WCLAUSE := LV_WCLAUSE || ' BLART = ' || '''' || IP_DOC_TYPE || '''';  --QA247 issue fix
 END IF ;
 IF IP_GL != '' THEN
  if LV_WCLAUSE = '' THEN 
   LV_WCLAUSE := LV_WCLAUSE || IP_GL;
  else
    LV_WCLAUSE := LV_WCLAUSE || ' AND ' || IP_GL;
  END IF ;  
 END IF ; 
--QA247 Issue fix start
 IF IP_WW220 != '' THEN
  if LV_WCLAUSE = '' THEN 
   LV_WCLAUSE := LV_WCLAUSE || IP_WW220;
  else
    LV_WCLAUSE := LV_WCLAUSE || ' AND ' || IP_WW220;
  END IF ;  
 END IF ; 
 
  IF IP_WW223 != '' THEN
  if LV_WCLAUSE = '' THEN 
   LV_WCLAUSE := LV_WCLAUSE || IP_WW223;
  else
    LV_WCLAUSE := LV_WCLAUSE || ' AND ' || IP_WW223;
  END IF ;  
 END IF ; 
 
  IF IP_WW214 != '' THEN
  if LV_WCLAUSE = '' THEN 
   LV_WCLAUSE := LV_WCLAUSE || IP_WW214;
  else
    LV_WCLAUSE := LV_WCLAUSE || ' AND ' || IP_WW214;
  END IF ;  
 END IF ;    
 --QA247 Issue fix END
 
 --QA257 issue fix start
 IF IP_PGL != '' THEN
 if LV_WCLAUSE = '' THEN 
   LV_WCLAUSE := LV_WCLAUSE || ' POST_GL = ' || '''' || IP_PGL || '''';
  else
    LV_WCLAUSE := LV_WCLAUSE || ' AND POST_GL = ' || '''' || IP_PGL || '''';
  END IF ;  
 END IF ;
 
 --QA257 Issue fix End
 
 select TOP 1 PERIO INTO LV_PERIO from :IP_RES;
 select TOP 1 BUKRS INTO LV_BUKRS from :IP_RES;
 
 select count(*) into LV_COUNT from "CCEJ_VIRTUAL"."ZJ_SUPP_COPA"  where PERIO = :LV_PERIO and VRGAR = 'N';
 if LV_COUNT != 0 THEN
 if LV_WCLAUSE = '' THEN 
   delete from "CCEJ_VIRTUAL"."ZJ_SUPP_COPA"  where PERIO = :LV_PERIO and BUKRS = :LV_BUKRS and VRGAR = 'N'; 
  else
  LV_SQL := 'delete from "CCEJ_VIRTUAL"."ZJ_SUPP_COPA"  where PERIO =' || '''' || :LV_PERIO || '''' || ' AND BUKRS = ' || '''' || :LV_BUKRS || '''';
  LV_SQL := LV_SQL || ' AND VRGAR = ' || '''' || 'N' || '''' || ' AND ' || :LV_WCLAUSE;
  EXECUTE IMMEDIATE LV_SQL;
  END IF ;
  EXEC 'COMMIT';
 end if;
 
 
 UPSERT "CCEJ_VIRTUAL"."ZJ_SUPP_COPA"  (MANDT,
PALEDGER,
VRGAR,
PERIO,
BELNR,
POSNR,
GJAHR,
BUDAT,
KNDNR,
ARTNR,
BUKRS,
KOKRS,
WERKS,
VKORG,
VTWEG,
SPART,
PRCTR,
WW207,
WW214,
WW220,
WW223,
VV557,
VV582,
VV529,
BLART,
EXPENSE_GL,
WW233,
WW237,
KSTAR,
POST_GL,
CRDATE,
CRTIME,
CRNAME) 
select 
'100' AS MANDT,
PALEDGER,
VRGAR,
PERIO,
BELNR,
POSNR,
GJAHR,
BUDAT,
KNDNR,
ARTNR,
BUKRS,
KOKRS,
WERKS,
VKORG,
VTWEG,
SPART,
PRCTR,
WW207,
WW214,
WW220,
WW223,
(VV557/100) AS VV557,
(VV582/100) AS VV582,
(VV529/100) AS VV529,
BLART,
EXPENSE_GL,
coalesce(WW233,'') AS WW233,
coalesce(WW237,'') AS WW237,
coalesce(KSTAR,'') AS KSTAR,
POST_GL,
CRDATE,
CRTIME,
CRNAME
 from :IP_RES;

EXEC 'COMMIT';

 
END;
