CREATE PROCEDURE "CCEJ_VIRTUAL"."ZJ_AccountPL.SupportFee::SUPPORT_FEE_STATGING_ACDOCNR" (IN P_GJAHR NVARCHAR(4) , IN P_FISCPER NVARCHAR(3),
IN P_LANGU NVARCHAR(1)  ) 
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER 
--DEFAULT SCHEMA <default_schema_name>
--READS SQL DATA 
AS
BEGIN
/***************************** 
EJX9005556--SUPPORT_FEE_STATGING_AC_DOC_NR 3/28/2025
 *****************************/
 
 TRUNCATE TABLE "CCEJ_VIRTUAL"."ZJ_AccountPL.SupportFee::ZJAPL_STAGING_ACDOCNR";
 
 INSERT INTO "CCEJ_VIRTUAL"."ZJ_AccountPL.SupportFee::ZJAPL_STAGING_ACDOCNR"
 (SELECT DISTINCT AC_DOC_NR
FROM "_SYS_BIC"."ZJ_AccountPL.SupportFee/ZJ_SUPPORT_FEE_DATA_F_001"
(PLACEHOLDER."$$IP_PERIOD$$" => :P_FISCPER,
PLACEHOLDER."$$IP_YEAR$$" => :P_GJAHR,
PLACEHOLDER."$$IP_LANGU$$" => :P_LANGU) where ZJ_FLAG = 'X');
 
END;
