CREATE PROCEDURE "CCEJ_VIRTUAL"."ZJ_AccountPL.SupportFee::GET_SUPPORT_FEE_COPA_DATA_POSTING" (IN P_GJAHR NVARCHAR(4) , IN P_FISCPER NVARCHAR(3) ,IN P_LANGU NVARCHAR(1),
IN P_COMP_CODE NVARCHAR(4) ,  IN P_AC_DOC_TYP NCLOB , IN P_GL_ACCOUNT NCLOB , IN P_CHANNEL NCLOB , IN P_RPPCAT NCLOB , 
IN P_BAC NCLOB ,IN P_SOURCE NVARCHAR(10),
--OUT P_RESULT_TEMP  "CCEJ_VIRTUAL"."ZJ_SUPPORT_FEE_PER",
OUT P_RESULT TABLE("BLART" NVARCHAR(2),
 "SOURCE" NVARCHAR(25),
 "EXPENSE_GL" NVARCHAR(10),
 "RPPCAT" NVARCHAR(3),
 "CHANNEL" NVARCHAR(3),
 "INCIDENT_PER" DECIMAL(8,2),
 "CREDIT_GL" NVARCHAR(10),
 "DEBIT_GL" NVARCHAR(10),
 "FI_DOCNR" NVARCHAR(10),
 "COPA_DOCNR" NVARCHAR(10),
 "COST" DECIMAL(15,2),
 "COPA_COST" DECIMAL(15,2),
 "COPA_SUPPFEE" DECIMAL(15,2),
 "PRCTR" NVARCHAR(10),
 "BAC" NVARCHAR(7),
 "ACC_CODE" NVARCHAR(4),
 "CCJCACC" NVARCHAR(10),
 "SUPPORT_FEE" DECIMAL(15,2),
 "RYEAR" NVARCHAR(4),
 "KOSTL" NVARCHAR(10),
 "RBELN" NVARCHAR(10),
 "VKORG" NVARCHAR(4),
 "VTWEG" NVARCHAR(2),
 "SPART" NVARCHAR(2),
 "DEALER" NVARCHAR(10),
 "WERKS" NVARCHAR(4),
 "SKU" NVARCHAR(18),
 "VALUE_FIELD" NVARCHAR(30),
 "REF_ITEMNO" NVARCHAR(6),
 "CUSTOMER" NVARCHAR(10),
 "TAX_CODE" NVARCHAR(2),
 "PERIOD" NVARCHAR(3),
 "BUKRS" NVARCHAR(4),
 "ROW_NUM" NVARCHAR(6),
 "WW233" NVARCHAR(3),
 "WW237" NVARCHAR(3))  ) 
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER 
--DEFAULT SCHEMA <default_schema_name>
--READS SQL DATA 
AS
BEGIN
/***************************** 
Write your procedure logic 
 *****************************/
 
DECLARE v_filter NCLOB := '' ;
Declare P_RESULT_TEMP  TABLE("BLART" NVARCHAR(2),
 "SOURCE" NVARCHAR(25),
 "EXPENSE_GL" NVARCHAR(10),
 "RPPCAT" NVARCHAR(3),
 "CHANNEL" NVARCHAR(3),
 "INCIDENT_PER" DECIMAL(8,2),
 "CREDIT_GL" NVARCHAR(10),
 "DEBIT_GL" NVARCHAR(10),
 "FI_DOCNR" NVARCHAR(10),
 "COPA_DOCNR" NVARCHAR(10),
 "COST" DECIMAL(15,2),
 "COPA_COST" DECIMAL(15,2),
 "COPA_SUPPFEE" DECIMAL(15,2),
 "PRCTR" NVARCHAR(10),
 "BAC" NVARCHAR(7),
 "ACC_CODE" NVARCHAR(4),
 "CCJCACC" NVARCHAR(10),
 "SUPPORT_FEE" DECIMAL(15,2),
 "RYEAR" NVARCHAR(4),
 "KOSTL" NVARCHAR(10),
 "RBELN" NVARCHAR(10),
 "VKORG" NVARCHAR(4),
 "VTWEG" NVARCHAR(2),
 "SPART" NVARCHAR(2),
 "DEALER" NVARCHAR(10),
 "WERKS" NVARCHAR(4),
 "SKU" NVARCHAR(18),
 "VALUE_FIELD" NVARCHAR(30),
 "REF_ITEMNO" NVARCHAR(6),
 "CUSTOMER" NVARCHAR(10),
 "TAX_CODE" NVARCHAR(2),
 "PERIOD" NVARCHAR(3),
 "BUKRS" NVARCHAR(4),
 "ROW_NUM" NVARCHAR(6),
 "WW233" NVARCHAR(3),
 "WW237" NVARCHAR(3));
 
IF P_SOURCE IS NULL or P_SOURCE = '' THEN 
 P_RESULT_TEMP = SELECT
 BLART,
 SOURCE,
 EXPENSE_GL,
 RPPCAT,
 CHANNEL,
 0 AS INCIDENT_PER,
 CREDIT_GL,
 DEBIT_GL,
 FI_DOCNR,
 COPA_DOCNR,
 SUM(COST) as COST ,
 SUM( COPA_COST) as COPA_COST,
 0 AS COPA_SUPPFEE,
 PRCTR,
 BAC,
 ACC_CODE,
 CCJCACC,
 0 AS SUPPORT_FEE ,
 RYEAR,
 KOSTL,
 RBELN,
 VKORG,
 VTWEG,
 SPART,
 DEALER,
 WERKS,
 SKU,
 VALUE_FIELD,
 '' AS REF_ITEMNO,
 CUSTOMER,
 TAX_CODE,
 "PERIOD",
 BUKRS,
 TO_CHAR(ROW_NUMBER () OVER (PARTITION BY FI_DOCNR ,RBELN,COPA_DOCNR 
 ORDER BY FI_DOCNR, RBELN,COPA_DOCNR )) AS ROW_NUM,
 WW233,
 WW237 
FROM "CCEJ_VIRTUAL"."ZJ_SUPPORT_FEE_PER" 
GROUP BY BLART,
 SOURCE,
 EXPENSE_GL,
 RPPCAT,
 CHANNEL,
 CREDIT_GL,
 DEBIT_GL,
 FI_DOCNR,
 COPA_DOCNR,
 PRCTR,
 BAC,
 ACC_CODE,
 CCJCACC,
 RYEAR,
 KOSTL,
 RBELN,
 VKORG,
 VTWEG,
 SPART,
 DEALER,
 WERKS,
 SKU,
 VALUE_FIELD,
 CUSTOMER,
 TAX_CODE,
 "PERIOD",
 BUKRS,
 WW233,
 WW237
;

ELSEIF P_SOURCE = 'FI' THEN 
 P_RESULT_TEMP =  SELECT
 BLART,
 SOURCE,
 EXPENSE_GL,
 RPPCAT,
 CHANNEL,
 0 AS INCIDENT_PER,
 CREDIT_GL,
 DEBIT_GL,
 FI_DOCNR,
 COPA_DOCNR,
 SUM(COST) as COST ,
 SUM( COPA_COST) as COPA_COST,
 0 AS COPA_SUPPFEE,
 PRCTR,
 BAC,
 ACC_CODE,
 CCJCACC,
 0 AS SUPPORT_FEE ,
 RYEAR,
 KOSTL,
 RBELN,
 VKORG,
 VTWEG,
 SPART,
 DEALER,
 WERKS,
 SKU,
 VALUE_FIELD,
 '' AS REF_ITEMNO,
 CUSTOMER,
 TAX_CODE,
 "PERIOD",
 BUKRS,
 TO_CHAR(ROW_NUMBER () OVER (PARTITION BY FI_DOCNR ,RBELN,COPA_DOCNR 
 ORDER BY FI_DOCNR, RBELN,COPA_DOCNR )) AS ROW_NUM,
 WW233,
 WW237 
FROM "CCEJ_VIRTUAL"."ZJ_SUPPORT_FEE_PER" 
WHERE SOURCE = 'FI'
GROUP BY BLART,
 SOURCE,
 EXPENSE_GL,
 RPPCAT,
 CHANNEL,
 CREDIT_GL,
 DEBIT_GL,
 FI_DOCNR,
 COPA_DOCNR,
 PRCTR,
 BAC,
 ACC_CODE,
 CCJCACC,
 RYEAR,
 KOSTL,
 RBELN,
 VKORG,
 VTWEG,
 SPART,
 DEALER,
 WERKS,
 SKU,
 VALUE_FIELD,
 CUSTOMER,
 TAX_CODE,
 "PERIOD",
 BUKRS,
 WW233,
 WW237
;

ELSEIF P_SOURCE = 'COPA' THEN
  P_RESULT_TEMP =  SELECT
 BLART,
 SOURCE,
 EXPENSE_GL,
 RPPCAT,
 CHANNEL,
 0 AS INCIDENT_PER,
 CREDIT_GL,
 DEBIT_GL,
 FI_DOCNR,
 COPA_DOCNR,
 SUM(COST) as COST ,
 SUM( COPA_COST) as COPA_COST,
 0 AS COPA_SUPPFEE,
 PRCTR,
 BAC,
 ACC_CODE,
 CCJCACC,
 0 AS SUPPORT_FEE ,
 RYEAR,
 KOSTL,
 RBELN,
 VKORG,
 VTWEG,
 SPART,
 DEALER,
 WERKS,
 SKU,
 VALUE_FIELD,
 '' AS REF_ITEMNO,
 CUSTOMER,
 TAX_CODE,
 "PERIOD",
 BUKRS,
 TO_CHAR(ROW_NUMBER () OVER (PARTITION BY FI_DOCNR ,RBELN,COPA_DOCNR 
 ORDER BY FI_DOCNR, RBELN,COPA_DOCNR )) AS ROW_NUM,
 WW233,
 WW237 
FROM "CCEJ_VIRTUAL"."ZJ_SUPPORT_FEE_PER" 
WHERE SOURCE = 'COPA'
GROUP BY BLART,
 SOURCE,
 EXPENSE_GL,
 RPPCAT,
 CHANNEL,
 CREDIT_GL,
 DEBIT_GL,
 FI_DOCNR,
 COPA_DOCNR,
 PRCTR,
 BAC,
 ACC_CODE,
 CCJCACC,
 RYEAR,
 KOSTL,
 RBELN,
 VKORG,
 VTWEG,
 SPART,
 DEALER,
 WERKS,
 SKU,
 VALUE_FIELD,
 CUSTOMER,
 TAX_CODE,
 "PERIOD",
 BUKRS,
 WW233,
 WW237
;
END IF ;


---Apply Filtering based on the Selection screen

v_filter := :P_AC_DOC_TYP ;
   
     if :P_GL_ACCOUNT  != ''  then
   
   if :v_filter != ''  then
   
   v_filter := v_filter || ' AND ' || :P_GL_ACCOUNT ;
   
  else 
  v_filter :=  :P_GL_ACCOUNT ;
  end if;

  end if ;
   
   
  if :P_CHANNEL  != ''  then
   
   if :v_filter != ''  then
   
  v_filter := v_filter || ' AND ' || :P_CHANNEL ;
   
  else 
  v_filter :=  :P_CHANNEL ;
  end if;

  end if ;
   
  if :P_RPPCAT  != ''  then
   
    if :v_filter != ''  then
  v_filter := v_filter || ' AND ' || :P_RPPCAT ;
   
  else 
  v_filter :=  :P_RPPCAT ;
  end if;

  end if ;
   
   
  if :P_BAC  != ''  then
   
  if :v_filter != ''  then
  v_filter := v_filter || ' AND ' || :P_BAC ;
  else 
  v_filter :=  :P_BAC ;
  end if;

  end if ;
      
 P_RESULT =  apply_filter( :P_RESULT_TEMP  , :v_filter  ) ;  



END;
