*&---------------------------------------------------------------------*
*& REPORT  ZXF01U01
*&---------------------------------------------------------------------*
* CUSTOMER              : GAIL                                         *
* PROGRAM NAME          : ZXF01U01                                     *
* DEVELOPMENT CLASS     : YF01                                         *
* TRANSPORT REQUEST NO  : DVRK9A09UN                                   *
* INITIATED BY          : GAURAV SHARMA / MR. KHICHI                   *
* DEVELOPED BY          : BIPIN SHUKLA                                 *
* VERSION NO            : V 1.0                                        *
* PROGRAM DESCRIPTION   : EBS USER EXIT                                *
* MODIFICATION HISTORY  :                                              *
* DATE               PERSON              REMARKS                       *
************************************************************************
* DD.MM.YYYY                                                           *
************************************************************************
*                                                                      *
*                                                                      *
*----------------------------------------------------------------------*
TABLES: YFIBANK_EBS.

DATA: IT_ZFIBANK_EBS TYPE TABLE OF YFIBANK_EBS,
      WA_ZFIBANK_EBS TYPE YFIBANK_EBS,
      LV_DUMMY       TYPE STRING,
      LV_AT          TYPE STRING,
      LV_TEXT        TYPE STRING,
      IT_BSIS        TYPE STANDARD TABLE OF BSIS,
      WA_BSIS        TYPE BSIS,
      LV_SHKZG       TYPE BSIS-SHKZG,
      LV_HKONT       TYPE BSIS-HKONT,
      E_ZUONR        TYPE DZUONR,
      LV_ZUONR       TYPE DZUONR,
      LV_ZUONR2      TYPE DZUONR,
      LV_LENGTH      TYPE I,
      LV_POS         TYPE N,
      LV_OFFSET      TYPE I,
      IT_FEBCL       TYPE TABLE OF FEBCL,
      WA_FEBCL       TYPE FEBCL,
      LV_INDEX       TYPE SY-TABIX,
      WA_FEBRE       TYPE FEBRE,
      FLAG           TYPE C VALUE '',
      WA_KNA1        TYPE KNA1,
      LV_VWEZW       TYPE STRING.

DATA : LV_LEN TYPE I.
DATA : LW_ZUONR TYPE DZUONR.
DATA : BEGIN OF LW_REFERENZ,
         KUKEY TYPE KUKEY_EB,
         ESNUM TYPE ESNUM_EB,
         ZUONR TYPE DZUONR,
       END OF LW_REFERENZ,
       LI_REFERENZ LIKE STANDARD TABLE OF LW_REFERENZ.

DATA : INDXKEY TYPE INDX-SRTFD VALUE 'EBS'.
TABLES : INDX.

FIELD-SYMBOLS: <FS_FEBCL> TYPE FEBCL.

BREAK XSAP_FI.
BREAK XGAIL_AB2.

* COPY THE FEBEP( ELECTRONIC BANK STATEMENT LINE ITEMS )
*E_FEBEP = I_FEBEP.
* GET THE ORIGINAL REFERENCE FROM DATABASE , WHICH WAS POPULATED IN
* BADI ZENH_FI_H2H_DECODE .

IMPORT LI_REFERENZ FROM DATABASE INDX(ST) ID INDXKEY.
CHECK LI_REFERENZ[] IS NOT INITIAL.
SORT LI_REFERENZ BY KUKEY ESNUM.

READ TABLE LI_REFERENZ
INTO LW_REFERENZ
WITH KEY KUKEY = I_FEBEP-KUKEY
         ESNUM = I_FEBEP-ESNUM BINARY SEARCH.
**CHECK SY-SUBRC EQ 0.

*** SOC BY AISHWARYA AND SANDEEP SINGH 18.09.23
DATA: REF_LEN TYPE I.
REF_LEN = STRLEN( LW_REFERENZ-ZUONR ).
*** -> BEGIN OF CHANGES BY OF HARSH ON 17OCT-24 FOR ATC
IF I_FEBEP-TEXTS = 'NCOL' AND I_FEBKO-VGTYP = 'ICICI940'. "#EC CI_USAGE_OK[2689873]
*** <- END CHANGES BY OF HARSH ON 17OCT-24 FOR ATC
  IF REF_LEN GT 8.
    REF_LEN = REF_LEN - 8.
    LW_REFERENZ-ZUONR = LW_REFERENZ-ZUONR+REF_LEN(8).
  ENDIF.
ENDIF.

DATA : LT_T012K TYPE STANDARD TABLE OF T012K,
       LV_TEXT2 TYPE CHAR200,
       LV_TABIX TYPE SY-TABIX.
RANGES : S_BUKRS FOR T012K-BUKRS.
S_BUKRS-SIGN    = 'I'.
S_BUKRS-OPTION  = 'BT'.
S_BUKRS-LOW     = '1000'.
S_BUKRS-HIGH    = '8000'.
APPEND S_BUKRS.

IF I_FEBEP-TEXTS = 'NSTO' AND I_FEBKO-VGTYP = 'ICICI940'.
  SELECT * FROM T012K INTO TABLE LT_T012K
                     WHERE BUKRS IN S_BUKRS.
  LOOP AT T_FEBRE INTO DATA(LS_FEBRE) WHERE KUKEY = I_FEBEP-KUKEY AND
                                            ESNUM = I_FEBEP-ESNUM.
    LOOP AT LT_T012K INTO DATA(LS_T012K).
      SEARCH LS_FEBRE-VWEZW FOR LS_T012K-BANKN.
      IF SY-SUBRC = 0.
        CONCATENATE LS_T012K-BANKN '-SWEEP' INTO DATA(LV_SGTXT).
        I_FEBEP-SGTXT = LV_SGTXT.
      ENDIF.
      CLEAR : LV_SGTXT,LS_T012K.
    ENDLOOP.
    CLEAR : LS_FEBRE.
  ENDLOOP.
ENDIF.

*** -> BEGIN OF CHANGES BY OF HARSH ON 17OCT-24 FOR ATC
IF I_FEBEP-TEXTS = 'NCOL' AND I_FEBKO-VGTYP = 'ICICI940'. "#EC CI_USAGE_OK[2689873]
*** <- END CHANGES BY OF HARSH ON 17OCT-24 FOR ATC
  LOOP AT T_FEBRE INTO DATA(LS_FEBRE2) WHERE KUKEY = I_FEBEP-KUKEY AND
                                             ESNUM = I_FEBEP-ESNUM.
    IF I_FEBEP-SGTXT IS INITIAL.
      SEARCH LS_FEBRE2-VWEZW FOR  'NEFT'.
      IF SY-SUBRC = 0.
        READ TABLE T_FEBRE TRANSPORTING NO FIELDS WITH KEY  KUKEY = I_FEBEP-KUKEY
                                                            ESNUM = I_FEBEP-ESNUM.
        LV_TEXT2 = LS_FEBRE2-VWEZW.
*        SPLIT LV_TEXT2 AT 'NEFT' INTO DATA(LV_VAR1) DATA(LV_VAR2).
        SPLIT LV_TEXT2 AT 'ICGAIL' INTO DATA(LV_VAR1) DATA(LV_VAR2).
        IF SY-SUBRC EQ 0.
*        LV_TABIX = SY-TABIX + 1.
*        LV_VAR2 = LV_VAR2 && SPACE && T_FEBRE[ LV_TABIX ]-VWEZW.
         LV_VAR2 = 'ICGAIL' && LV_VAR2.
        IF  SY-SUBRC = 0.
          CLEAR : LV_LEN.
          LV_LEN = STRLEN( LV_VAR2 ).
          IF LV_LEN GT 50.
          I_FEBEP-SGTXT = LV_VAR2+0(50).
          ELSE.
          I_FEBEP-SGTXT = LV_VAR2.
          ENDIF.
        ENDIF.
        ELSE.
        SPLIT LV_TEXT2 AT 'NEFT' INTO LV_VAR1 LV_VAR2.
        LV_TABIX = SY-TABIX + 1.
        LV_VAR2 = LV_VAR2 && SPACE && T_FEBRE[ LV_TABIX ]-VWEZW.
        IF  SY-SUBRC = 0.
          CLEAR : LV_LEN.
          LV_LEN = STRLEN( LV_VAR2 ).
          IF LV_LEN GT 50.
          I_FEBEP-SGTXT = LV_VAR2+0(50).
          ELSE.
          I_FEBEP-SGTXT = LV_VAR2.
          ENDIF.
        ENDIF.
        ENDIF.
      ELSE.
        SEARCH LS_FEBRE2-VWEZW FOR  'RTGS'.
        IF SY-SUBRC = 0.
          READ TABLE T_FEBRE TRANSPORTING NO FIELDS WITH KEY  KUKEY = I_FEBEP-KUKEY
                                                            ESNUM = I_FEBEP-ESNUM.
          LV_TEXT2 = LS_FEBRE2-VWEZW.
*          SPLIT LV_TEXT2 AT 'RTGS' INTO LV_VAR1 LV_VAR2.
          SPLIT LV_TEXT2 AT 'ICGAIL' INTO LV_VAR1 LV_VAR2.
          IF SY-SUBRC EQ 0.
*          LV_TABIX = SY-TABIX + 1.
*          LV_VAR2 = LV_VAR2 && SPACE && T_FEBRE[ LV_TABIX ]-VWEZW.
          LV_VAR2 = 'ICGAIL' && LV_VAR2.
          IF SY-SUBRC = 0.
          CLEAR : LV_LEN.
          LV_LEN = STRLEN( LV_VAR2 ).
          IF LV_LEN GT 50.
            I_FEBEP-SGTXT = LV_VAR2+0(50).
          ELSE.
            I_FEBEP-SGTXT = LV_VAR2.
          ENDIF.
          ENDIF.
         ELSE.
         SPLIT LV_TEXT2 AT 'RTGS' INTO LV_VAR1 LV_VAR2.
         LV_TABIX = SY-TABIX + 1.
         LV_VAR2 = LV_VAR2 && SPACE && T_FEBRE[ LV_TABIX ]-VWEZW.
         IF SY-SUBRC = 0.
          CLEAR : LV_LEN.
          LV_LEN = STRLEN( LV_VAR2 ).
          IF LV_LEN GT 50.
            I_FEBEP-SGTXT = LV_VAR2+0(50).
          ELSE.
            I_FEBEP-SGTXT = LV_VAR2.
          ENDIF.
          ENDIF.
         ENDIF.
        ENDIF.
      ENDIF.
      CLEAR : LS_FEBRE2,LV_TEXT2,LV_VAR1,LV_VAR2,LV_TABIX.
    ENDIF.
  ENDLOOP.
ENDIF.
CLEAR S_BUKRS.

E_FEBEP = I_FEBEP.
IF SY-SUBRC = 0.
*CHECK LW_REFERENZ[] IS NOT INITIAL. " CHECK IF IT IS COMING FROM 61 TAG IN FILE.
**REPLACE THE ASSIGNMENT FIELD WITH ORIGINAL REFERENCE COMING FROM BANK FILE.
*SORT LI_REFERENZ BY KUKEY ESNUM.
  E_FEBEP-ZUONR = LW_REFERENZ-ZUONR.
*REPLACE THE ASSIGNMENT FIELD IN FEBCL WITH ORIGINAL REFERENCE COMING FROM BANK.
  LOOP AT T_FEBCL ASSIGNING <FS_FEBCL> WHERE KUKEY EQ I_FEBEP-KUKEY
                                         AND ESNUM = I_FEBEP-ESNUM
                                         AND SELFD EQ 'ZUONR'.
    <FS_FEBCL>-SELVON = LW_REFERENZ-ZUONR.
  ENDLOOP.
ENDIF.

CLEAR: WA_ZFIBANK_EBS, WA_BSIS,LV_SHKZG,LV_HKONT .

E_FEBKO = I_FEBKO.

"SOC  : ON 24.09.2019 10:42:51 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA /  CHARM - 4000000848
*REASON  :THERE IS AN ISSUE COMING IN BRS THROUGH MT940 IN ICICI BANK, ENTRIES ARE NOT GETTING
**CLEARED EVEN THOUGH THE ASSIGNMENT IS MATCHING.WE WANT TO MATCH THE ENTRY AND TO BE
**RECONCILED AND CLEARED EVEN THOUGH THE AMOUNT DOES NOT MATCH BUT THE ASSIGNMENT NUMBER
**MATCHES SO THAT THE SYSTEM PASSES THE ENTRY OF THE DIFFERENTIAL AMOUNT AND CLEARS THE PAYMENT
**ENTRIES WITH THE BRS ENTRY IN BANK INCOMING AND OUTGOING GLS.

*** IF USERNAME IS FOUND THEN CHANGES LOGIC WILL WORK ELSE OLD LOGIC WILL WORK ********

DATA : GT_SET_MT940 TYPE TABLE OF RGSBV.

CALL FUNCTION 'G_SET_FETCH'
  EXPORTING
    CLASS           = '0000'
    LANGU           = SY-LANGU
*   NO_AUTHORITY_CHECK        = ' '
    SETNR           = 'YFI_MT940_EXCLUDE'
  TABLES
    SET_LINES_BASIC = GT_SET_MT940
  EXCEPTIONS
    NO_AUTHORITY    = 1
    SET_IS_BROKEN   = 2
    SET_NOT_FOUND   = 3
    OTHERS          = 4.

READ TABLE GT_SET_MT940 INTO DATA(GS_SET) WITH KEY FROM = SY-UNAME.
IF SY-SUBRC <> 0.

  "EOC  : ON 24.09.2019 10:43:01 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA / CHARM - 4000000848

  SELECT SINGLE *
    FROM YFIBANK_EBS
    INTO WA_ZFIBANK_EBS
    WHERE BANKN = E_FEBKO-KTONR.
  IF SY-SUBRC = 0.
    E_FEBEP-PRCTR = WA_ZFIBANK_EBS-PRCTR.
    IF E_FEBEP-EPVOZ = 'S'.
      LV_SHKZG = 'H'.
      LV_HKONT = WA_ZFIBANK_EBS-HKONT.
    ELSEIF E_FEBEP-EPVOZ = 'H'.
      LV_SHKZG  = 'S'.
      LV_HKONT = WA_ZFIBANK_EBS-ZHKONT.
    ENDIF.
    IF E_FEBEP-ZUONR IS NOT INITIAL.
      FIND FIRST OCCURRENCE OF 'NONREF' IN E_FEBEP-ZUONR.
      IF SY-SUBRC = 0.
        CLEAR: E_FEBEP-ZUONR.
      ELSE.
        FIND FIRST OCCURRENCE OF 'NONREF' IN E_FEBEP-ZUONR.
        IF SY-SUBRC = 0.
          CLEAR: E_FEBEP-ZUONR.
        ENDIF.
      ENDIF.
      LV_LENGTH = STRLEN( E_FEBEP-ZUONR ).
      E_ZUONR = E_FEBEP-ZUONR .
      CLEAR LV_POS.
      DO LV_LENGTH TIMES.
        IF E_ZUONR+LV_POS(1) CO '0123456789'.
*        CLEAR E_FEBEP-ZUONR+LV_POS(1).
          LV_OFFSET = LV_LENGTH - LV_POS.
          LV_ZUONR = E_ZUONR+LV_POS(LV_OFFSET).
          EXIT.
        ENDIF.
        LV_POS = LV_POS + 1.
      ENDDO.
    ENDIF.

*Begin of changes by of VIPUL on 20241104  for ATC
SELECT ZUONR
FROM bsis
INTO lv_zuonr2
UP TO 1 ROWS
WHERE bukrs = e_febko-bukrs
AND hkont = lv_hkont
AND zuonr = e_febep-zuonr
AND dmbtr = e_febep-kwbtr
AND shkzg = lv_shkzg ORDER BY bukrs .
ENDSELECT.
* *End of changes by of VIPUL on 20241104  for ATC
    IF SY-SUBRC NE 0.
*Begin of changes by of VIPUL on 20241104  for ATC
SELECT ZUONR
FROM bsis
INTO lv_zuonr2
UP TO 1 ROWS
WHERE bukrs = e_febko-bukrs
AND hkont = lv_hkont
AND zuonr = lv_zuonr
AND dmbtr = e_febep-kwbtr
AND shkzg = lv_shkzg ORDER BY bukrs .
ENDSELECT.
* *End of changes by of VIPUL on 20241104  for ATC
      IF SY-SUBRC = 0.
        E_FEBEP-CHECT =  LV_ZUONR2.
        E_FEBEP-ZUONR = LV_ZUONR2.
        CLEAR: WA_FEBCL.
        READ TABLE T_FEBCL INTO WA_FEBCL WITH KEY KUKEY = E_FEBEP-KUKEY.
        IF SY-SUBRC = 0.
          LV_INDEX = SY-TABIX.
          WA_FEBCL-SELVON = LV_ZUONR2.
          MODIFY T_FEBCL FROM WA_FEBCL INDEX LV_INDEX TRANSPORTING SELVON.
        ENDIF.
      ELSE.
        IF E_FEBEP-EPVOZ = 'S'.
          E_FEBEP-VGINT = WA_ZFIBANK_EBS-EIGR1.
          E_FEBEP-INTAG = 000.
        ELSEIF E_FEBEP-EPVOZ = 'H'.
          E_FEBEP-VGINT = WA_ZFIBANK_EBS-ZEIGR1.
          E_FEBEP-INTAG = 000.
        ENDIF.
      ENDIF.
    ELSE.
      E_FEBEP-CHECT =  LV_ZUONR2.
      E_FEBEP-ZUONR = LV_ZUONR2.
      CLEAR: WA_FEBCL.
      READ TABLE T_FEBCL INTO WA_FEBCL WITH KEY KUKEY = E_FEBEP-KUKEY.
      IF SY-SUBRC = 0.
        LV_INDEX = SY-TABIX.
        WA_FEBCL-SELVON = LV_ZUONR2.
        MODIFY T_FEBCL FROM WA_FEBCL INDEX LV_INDEX TRANSPORTING SELVON.
      ENDIF.
    ENDIF.

  ENDIF.

  "SOC  : ON 24.09.2019 10:43:01 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA / CHARM - 4000000848
ELSE.
  "EOC  : ON 24.09.2019 10:43:01 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA / CHARM - 4000000848

  "SOC  : CHANGE BLOCK A : ON 24.09.2019 10:43:01 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA / CHARM - 4000000848
***REASON : THIS IS THE BLOCK A WHERE CHANGES HAS BEEN CARRIED OUT TO TEST THE SCENARIO IN PRD AS NO TEST CASE FOUND
**           CHANGES CODE WILL WORK FOR THOSE ID MAINTAIN IN SET YFI_MT940_EXCLUDE
*
***
**THERE IS AN ISSUE COMING IN BRS THROUGH MT940 IN ICICI BANK, ENTRIES ARE NOT GETTING
**CLEARED EVEN THOUGH THE ASSIGNMENT IS MATCHING.WE WANT TO MATCH THE ENTRY AND TO BE
**RECONCILED AND CLEARED EVEN THOUGH THE AMOUNT DOES NOT MATCH BUT THE ASSIGNMENT NUMBER
**MATCHES SO THAT THE SYSTEM PASSES THE ENTRY OF THE DIFFERENTIAL AMOUNT AND CLEARS THE PAYMENT
**ENTRIES WITH THE BRS ENTRY IN BANK INCOMING AND OUTGOING GLS.

  SELECT SINGLE *
    FROM YFIBANK_EBS
    INTO WA_ZFIBANK_EBS
    WHERE BANKN = E_FEBKO-KTONR.
  IF SY-SUBRC = 0.
    E_FEBEP-PRCTR = WA_ZFIBANK_EBS-PRCTR.
    IF E_FEBEP-EPVOZ = 'S'.
      LV_SHKZG = 'H'.
      LV_HKONT = WA_ZFIBANK_EBS-HKONT.
    ELSEIF E_FEBEP-EPVOZ = 'H'.
      LV_SHKZG  = 'S'.
      LV_HKONT = WA_ZFIBANK_EBS-ZHKONT.
    ENDIF.
    IF E_FEBEP-ZUONR IS NOT INITIAL.
      FIND FIRST OCCURRENCE OF 'NONREF' IN E_FEBEP-ZUONR.
      IF SY-SUBRC = 0.
        CLEAR: E_FEBEP-ZUONR.
      ELSE.
        FIND FIRST OCCURRENCE OF 'NONREF' IN E_FEBEP-ZUONR.
        IF SY-SUBRC = 0.
          CLEAR: E_FEBEP-ZUONR.
        ENDIF.
      ENDIF.
      LV_LENGTH = STRLEN( E_FEBEP-ZUONR ).
      E_ZUONR = E_FEBEP-ZUONR .
      CLEAR LV_POS.
      DO LV_LENGTH TIMES.
        IF E_ZUONR+LV_POS(1) CO '0123456789'.
*        CLEAR E_FEBEP-ZUONR+LV_POS(1).
          LV_OFFSET = LV_LENGTH - LV_POS.
          LV_ZUONR = E_ZUONR+LV_POS(LV_OFFSET).
          EXIT.
        ENDIF.
        LV_POS = LV_POS + 1.
      ENDDO.
    ENDIF.

    "SOCOMMENTING : ON 29.08.2019 11:14:58 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA  CHARM - 4000000848
*  * REASON :
*  SELECT SINGLE ZUONR
*    FROM BSIS
*    INTO LV_ZUONR2
*    WHERE BUKRS = E_FEBKO-BUKRS
*    AND HKONT = LV_HKONT
*    AND ZUONR = E_FEBEP-ZUONR
*    AND DMBTR = E_FEBEP-KWBTR
*    AND SHKZG = LV_SHKZG.
    "EOCOMMENTING : ON 29.08.2019 11:15:12 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA   CHARM - 4000000848

    "SOC  : ON 29.08.2019 11:14:58 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA  CHARM - 4000000848
*   * REASON :
    DATA LV_KWBTR TYPE KWBTR.

    "SOC : ON 18.10.2019 13:55:43 BY TAPAN SANTI / SUNNY BABLA CHARM # - 4000000980
**REASON : COMMENTING CODE FOR AUTO POSTING AFTER CLEARING FAIL

**      SELECT DMBTR , ZUONR , SHKZG
**        FROM BSIS
**        INTO TABLE @DATA(LT_BSIS)
**        WHERE BUKRS = @E_FEBKO-BUKRS
**        AND HKONT = @LV_HKONT
**        AND ZUONR = @E_FEBEP-ZUONR.
**
**      LOOP AT LT_BSIS INTO DATA(LS_BSIS).
**        IF LS_BSIS-SHKZG = 'S'.
**          LS_BSIS-DMBTR = LS_BSIS-DMBTR * 1.
**        ELSE.
**          LS_BSIS-DMBTR = LS_BSIS-DMBTR * -1.
**        ENDIF.
**        LV_KWBTR =  LV_KWBTR +  LS_BSIS-DMBTR.
**      ENDLOOP.
*"EOC : ON 18.10.2019 13:55:43 BY TAPAN SANTI / SUNNY BABLA CHARM # - 4000000980
**REASON : COMMENTING CODE FOR AUTO POSTING AFTER CLEARING FAIL

  ENDIF.

  "SOC  : ON 24.09.2019 10:46:24 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA /   CHARM - 4000000848
* REASON :
ENDIF.
"EOC  : ON 24.09.2019 10:47:13 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA /  CHARM - 4000000848

"EOC  : CHANGE BLOCK A : ON 24.09.2019 10:43:01 BY MAN MOHAN ACHARYA / SUNNY BABLA / VEERA SAMUDRALA / CHARM - 4000000848

**SOC     :  ON26.04.2019 15:55:58   BY  MAN MOHAN ACHARYA /  PANKAJ GUPTA / SUNNY BABLA
"+++++OVERWRITE ZUONR FOR SWEEP CODE.
*IF LS_TEMP_FEBEP-TEXTS = 'NSTO'.
*  E_FEBEP-ZUONR = LS_TEMP_FEBEP-ZUONR.
*ENDIF.
DATA: BEGIN OF LT_XFEBEP OCCURS 100.
        INCLUDE STRUCTURE FEBEP.
      DATA: END OF LT_XFEBEP.
** -> BEGIN OF CHANGES BY  KRITIKA ON 23.10.2024 FOR ATC
IMPORT LT_XFEBEP FROM MEMORY ID 'YRFEKA400_XFEBEP[]'. "#EC CI_FLDEXT_OK[2610650]
** <- END OF CHANGES BY KRITIKA ON 23.10.2024 FOR ATC

READ TABLE LT_XFEBEP INTO DATA(LS_XFEBEP) WITH KEY  KUKEY = E_FEBEP-KUKEY ESNUM = E_FEBEP-ESNUM.
IF SY-SUBRC = 0.
  IF LS_XFEBEP-TEXTS = 'NSTO'.
    E_FEBEP-ZUONR = LS_XFEBEP-ZUONR.
  ENDIF.
ENDIF.
***EOC     :  ON26.04.2019 15:55:58   BY  MAN MOHAN ACHARYA /  PANKAJ GUPTA / SUNNY BABLA
